[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/fasthttp"

[[constraint]]
  branch = "master"
  name = "github.com/buaazp/fasthttprouter"
